import './globals.css';
import { Inter } from 'next/font/google';
import { WidthProvider } from '@/providers/WidthProvider';
import { ThemeProvider } from '@/providers/ThemeProvider';
import { cn } from '@/lib/utils';
import CarouselWrapper from '@/components/CarouselWrapper';
import Main from '@/components/Main';
import Header from '@/components/Header';
import Curtain from './Curtain';

const font = Inter({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          font.className,
          'antialiased min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-50'
        )}
      >
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <WidthProvider>
            <Header className='z-0 fixed -translate-x-1/2 left-1/2' />
            <Main className='absolute z-50 -translate-x-1/2 left-1/2'>{children}</Main>
            {/* <Curtain /> */}
            <CarouselWrapper className='z-0' />
          </WidthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
