site_url: https://reel-reflections.netlify.app
display_url: https://reel-reflections.netlify.app
logo_url: https://reel-reflections.netlify.app/logo-login.svg
backend:
  name: git-gateway
  branch: main
local_backend: true
media_folder: /public/images
public_folder: /images
collections:
  - name: pages
    label: Pages
    folder: '/content/pages'
    create: true
    identifier_field: title
    slug: '{{fields.title}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: posts
    label: Posts
    folder: '/content/posts'
    create: true
    identifier_field: title
    slug: '{{fields.title}}'
    fields:
      - { label: 'Movie Title', name: 'title', widget: 'string', required: true }
      - { label: 'Movie Release Date', name: 'release', widget: 'number', required: true }
      - { label: 'Article Title', name: 'article', widget: 'string', required: true }
      - { label: 'Article Creation Date', name: 'created', widget: 'datetime', required: true }
      - { label: 'Article Description', name: 'description', widget: 'string' }
      - { label: 'Movie Personal Rate', name: 'rating', widget: 'number' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
